kind: pipeline
name: default
type: docker

steps:
  - name: Perform Build
    image: ubuntu:20.04
    commands:
      - ./setup.sh
      - ./build.sh
      - ./deploy.sh
    environment:
      TARGET_API: 25
      ANDROID_PLATFORM: 22
      ANDROID_ABI: arm64-v8a
      BUILD_TOOLS_VERSION: 28.0.3
      NDK_VERSION: 20.1.5948944
      CMAKE_VERSION: 3.10.2.4988404
      DEBIAN_FRONTEND: noninteractive
      ANDROID_HOME: /opt/android-sdk-linux
      NEXUS_PWD:
        from_secret: NEXUS_PWD

trigger:
  ref:
    - refs/heads/**
